# Numpy Exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
a = np.array(range(10,49))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 3.  Using indexing, reverse a vector (first element becomes last) (★☆☆)

In [18]:
b = [a[len(a) -1 - index] for index,num in enumerate(a)]
b = np.array(b)
b

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 4.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [4]:
c = np.array(range(0,9)).reshape((3,3))
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.ndim(c)
#Dimensions of c

2

#### 5. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

hint: look into `np.nonzero()`

In [39]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 6. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [44]:
ra = np.random.random((10,10))
print(ra)
minmax= [np.min(ra), np.max(ra)]
minmax

[[0.97783659 0.75949146 0.45764129 0.24559462 0.8274163  0.92806551
  0.88654109 0.16229184 0.96753098 0.03038605]
 [0.88687904 0.09673979 0.28304483 0.62629723 0.68402936 0.75205587
  0.25878078 0.8077443  0.37163482 0.53201417]
 [0.50516272 0.48109592 0.28853178 0.36405436 0.18611834 0.08288117
  0.28919942 0.38703684 0.98021048 0.80697134]
 [0.9296791  0.86322544 0.07431432 0.5516264  0.70726304 0.8745121
  0.34231465 0.06521273 0.06774767 0.92528033]
 [0.4317301  0.08305818 0.20522134 0.5532888  0.24268114 0.00214022
  0.53121229 0.3191891  0.98034825 0.4405373 ]
 [0.59664249 0.42528602 0.86242842 0.31577975 0.10467685 0.76313725
  0.1603371  0.25206913 0.45857819 0.38268032]
 [0.53298541 0.55238912 0.03176287 0.61621901 0.92044502 0.67777432
  0.07978128 0.78596608 0.09703584 0.25365254]
 [0.80684183 0.21707509 0.70313053 0.12662749 0.81377803 0.78469496
  0.49272936 0.50096603 0.74015547 0.07363362]
 [0.45697063 0.25837307 0.53191068 0.10284047 0.41234708 0.58156947
  0.59490366 

[0.0021402155816080404, 0.980348247861989]

#### 7. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
rv = np.random.rand((30))
np.mean(rv)


0.5451159628085185

#### 8. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
x = np.zeros((1,1)) #If we put here 1 it is considered 1dim so the padding is only occurring in 1dimension too.
x
np.pad(x, (1,1), mode = 'constant', constant_values = 1)

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

Hint: look into `np.dot()`

In [23]:
m1 = np.array(range(0,15)).reshape((5,3))
m2 = np.array(range(0,6)).reshape((3,2))

np.dot(m1,m2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 10. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
Z = np.arange(11)
for i,num in enumerate(Z):
    if (3<i<8):
        Z[i] = - num
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [41]:
Z = np.arange(11)
Z = [-num for i,num in enumerate(Z) if (3<i<8)]
Z
#COULD YOU USE TWO CONDITIONS IN LIST COMPREHENSION?

[-4, -5, -6, -7]

#### 11. How to find common values between two arrays? (★☆☆)

Hint: loo into `np.intersect1d()`

In [56]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)

[0 6 2 5 1 3 3 9 0 8]
[6 8 1 0 4 2 0 1 3 5]


In [59]:
np.intersect1d(Z1,Z2)
#Esta función busca los valores de una que están en la otra y crea un array con todos ellos
#ordenados de menor a mayor

array([0, 1, 2, 3, 5, 6, 8])

#### 12. Create a random vector of size 10 and sort it (★★☆)
Hint: look into `np.sort()`

In [61]:
Z = np.random.random(10)
Z

array([0.27265142, 0.12385587, 0.82292793, 0.10060479, 0.61126426,
       0.98535498, 0.9938088 , 0.00260982, 0.96247384, 0.9991498 ])

In [63]:
newZ = np.sort(Z)
newZ

array([0.00260982, 0.10060479, 0.12385587, 0.27265142, 0.61126426,
       0.82292793, 0.96247384, 0.98535498, 0.9938088 , 0.9991498 ])

#### 13. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

Hint: look into `np.argmax()`

In [72]:
X = np.random.random(10)
X

array([0.06952154, 0.04521038, 0.40534844, 0.08541873, 0.74261899,
       0.41743195, 0.98036094, 0.09158931, 0.40351844, 0.56009658])

In [73]:
X[np.argmax(X)]=0
X

array([0.06952154, 0.04521038, 0.40534844, 0.08541873, 0.74261899,
       0.41743195, 0.        , 0.09158931, 0.40351844, 0.56009658])

#### 14. How to find the closest value (and its index) to a given scalar in a vector? (★★☆)

In [98]:
x = np.random.randint(0, 100, (20, 1))  # the data
num = 5  # change this number to test your code
print(x)

[[98]
 [63]
 [86]
 [ 4]
 [23]
 [79]
 [54]
 [26]
 [99]
 [21]
 [50]
 [48]
 [73]
 [43]
 [63]
 [79]
 [ 2]
 [18]
 [99]
 [65]]


In [99]:
#I am considering the fact that the closest value is the one that gives the smaller number if
#we substract one by the other (absolute value of that)
index = np.argmin(np.abs(x - num))
print ('The closest number is ' + str(x[index]) + ' its index is '+ str(index))

The closest number is [4] its index is 3


#### 15. How to convert a float (32 bits) array into an integer (32 bits) in place?

hint: look into `.astype()`

In [124]:
Z = np.arange(10, dtype=np.float32)
Z.dtype

dtype('float32')

In [133]:
b = Z.astype(dtype=np.int32)
b.dtype

dtype('int32')

#### 16. Subtract the mean of each row of a matrix (★★☆)

In [183]:
X = np.random.rand(5, 10)
X

array([[0.90950261, 0.53080414, 0.95125188, 0.31206683, 0.33021298,
        0.40397089, 0.04823254, 0.40539738, 0.74872342, 0.12589331],
       [0.5757024 , 0.07726187, 0.75551639, 0.25307654, 0.27202009,
        0.58341339, 0.39615672, 0.23868599, 0.28401191, 0.36928288],
       [0.02294442, 0.58640967, 0.83224101, 0.64888749, 0.05107085,
        0.68690732, 0.84397307, 0.60996917, 0.01003234, 0.5479508 ],
       [0.59134916, 0.69050083, 0.28516288, 0.2872147 , 0.99713242,
        0.29253001, 0.94691286, 0.17562085, 0.9899295 , 0.57845326],
       [0.00559615, 0.17242546, 0.47751663, 0.11578089, 0.77706111,
        0.02099639, 0.19644311, 0.84133896, 0.39957858, 0.56479384]])

In [178]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b =np.mean(a,axis=1) #así calculamos media en cada FILA, con axis=1
print(b)
c=[]

for i in range(0,(a.shape[0])):
    c.append (a[i,:]-i)
print(c)

[[1 2 3]
 [4 5 6]]
[2. 5.]
[array([1, 2, 3]), array([3, 4, 5])]


In [184]:
b =np.mean(X,axis=1) #así calculamos media en cada FILA, con axis=1
print(b)
c=[] #This is the new matrix in which I save the matrix of random numbers - the mean of each row

for i in range(0,(X.shape[0])):
    c.append (X[i,:]-b[i])
print(c)

[0.4766056  0.38051282 0.48403861 0.58348065 0.35715311]
[array([ 0.43289701,  0.05419854,  0.47464628, -0.16453877, -0.14639262,
       -0.0726347 , -0.42837306, -0.07120822,  0.27211782, -0.35071229]), array([ 0.19518958, -0.30325095,  0.37500357, -0.12743628, -0.10849273,
        0.20290058,  0.0156439 , -0.14182682, -0.09650091, -0.01122994]), array([-0.46109419,  0.10237106,  0.3482024 ,  0.16484887, -0.43296776,
        0.20286871,  0.35993446,  0.12593055, -0.47400627,  0.06391218]), array([ 0.00786851,  0.10702018, -0.29831777, -0.29626594,  0.41365177,
       -0.29095063,  0.36343222, -0.40785979,  0.40644885, -0.00502739]), array([-0.35155696, -0.18472765,  0.12036352, -0.24137222,  0.419908  ,
       -0.33615673, -0.16071001,  0.48418585,  0.04242547,  0.20764073])]


#### 17. How to sort an array by the nth column? (★★☆)

Hint: look into `.argsort()`

In [204]:
Z = np.random.randint(0,10,(3,3))
Z

array([[6, 6, 9],
       [5, 9, 6],
       [9, 2, 3]])

In [205]:
Z.argsort(0)
#this function gives the postions for sorting the array. 0 if columns, 1 if rows
#i.e. in each col/row includes positions 0-n in the place of the number

array([[1, 2, 2],
       [0, 0, 1],
       [2, 1, 0]], dtype=int64)

In [206]:
Ord = np.argsort(Z,axis=0) #Coordenadas de orden
print(Ord)
print(np.sort(Z,axis=0)) #Ordenados por columnas

[[1 2 2]
 [0 0 1]
 [2 1 0]]
[[5 2 3]
 [6 6 6]
 [9 9 9]]


In [194]:
help('numpy.argsort')

Help on function argsort in numpy:

numpy.argsort = argsort(a, axis=-1, kind='quicksort', order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will stil

In [202]:
help (np.sort)

Help on function sort in module numpy.core.fromnumeric:

sort(a, axis=-1, kind='quicksort', order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be used, in the order in which
        they come up in the dtype, to break ties.
    
    Returns
    -------
    sorted_array : ndarray
        Array of the same type and shape a

#### 18. How to find the most frequent value in an array? (★★☆)

In [396]:
Z = np.random.randint(0,10,50)
Z

array([3, 9, 2, 9, 7, 1, 2, 5, 8, 9, 0, 4, 9, 8, 1, 5, 1, 0, 0, 0, 1, 0,
       4, 6, 1, 4, 1, 9, 3, 5, 1, 3, 2, 4, 8, 2, 8, 3, 8, 9, 8, 5, 0, 3,
       0, 7, 9, 8, 6, 0])

In [399]:
nrnum = []
for num in Z:
    if (np.intersect1d(nrnum,num)).size == 0 :
        nrnum.append(num)        
print(nrnum)   
#This part is to obtain ana array with all the numbers in a non repetitive way
count =0;repeat=[];
for i,n in enumerate(nrnum):
    for j in Z:
        if n==j :
            count+=1
    repeat.append(count)
    count=0;
print (repeat)
#this list counts how many times the previous numbers appear in the sequence

maximos  = [nrnum[ind] for ind,r in enumerate(repeat) if max(repeat)== r]

print('The most frequent value or values: ' + str(maximos))

[3, 9, 2, 7, 1, 5, 8, 0, 4, 6]
[5, 7, 4, 2, 7, 4, 7, 8, 4, 2]
The most frequent value or values: [0]


In [348]:
np.argmax

In [398]:
A = [1, 2, 3, 4, 5]
B = A[1]
C =np.intersect1d(A,B)
print(C.size)

1


#### 19. How to swap two rows of an array? (★★★)

In [401]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [406]:
B = np.copy(A[1,:])
A [1,:] = A[2,:]
A[2,:] = B
A
#If we dont use np.copy, then the variable has not the fixed value, and if we change after A[1,:], 
#the variable B would also change

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 20. How to get the nth largest values of an array (★★★)

In [492]:
Z = []
Z = np.arange(20)
np.random.shuffle(Z)

Z

array([10,  8,  4,  6,  7,  9,  1, 11, 14, 16, 13,  3,  0, 19, 17, 12, 18,
        5,  2, 15])

In [493]:
n = 1
X = np.sort(Z) #this returns the oredered vector.
print(X)
numero = X[len(X)-n] #the position of the nth maximum will be the final - the nth entry. As they are ordered,
#we can use indexes
print(numero)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
19


In [474]:
help(np.argsort)

Help on function argsort in module numpy.core.fromnumeric:

argsort(a, axis=-1, kind='quicksort', order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields w

---

# Matplotlib Exercises

#### 21. Create a function that compute averages using a sliding window over an array? (★★★)

Note that the function accepts two inputs:
- the array, and
- the size of the window

In [89]:
def moving_average(Z, n):
    times = int(len(Z)/n)
    i1 = 0;
    i2 = n; 
    move = [];
    
    for i in range(0,times):
        move.append (np.mean(Z [i1 :i2]))
        i1= i2 ;
        i2 = i2 + n;
    
    if (i1) != (len(Z)) :
        move.append (np.mean(Z [i1:] ))

    return move
#this function will return the mean bet each n values but means do not overlap

In [101]:
def moving_average2(Z, n):
    times = int(len(Z)-2)
    i1 = 0;
    i2 = n; 
    move = [];
    
    for i in range(0,times):
        move.append (np.mean(Z [i1 :i2]))
        i1 += 1 ;
        i2 += 1;
    
    return move
#this returns all the averages in bet, overlaping

In [91]:
a = np.array([1,2,3,4,5,6])
print(np.mean(a[0:1]))
print(np.mean(a[2:4]))
print(np.mean(a[4:6]))
int

a [range(2)]

1.0
3.5
5.5


array([1, 2])

In [100]:
Z = np.arange(10)
print(moving_average2(Z, n=3))

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


#### 22. Create a square wave, and find out the time at which it state makes a transition (from 0 to 1 and vice versa)

Steps:
- create an array which has multiple 0s, 1s, 0s, 1s, etc.
- create another array which contains timing information (this is up to you)
- then find out at which exact times its state changes

In [120]:
sqwave = [0,0,0,1,0,1,1,1,0,0,1];
time = np.linspace(0,10,num = len(sqwave))
print(time)
tchange = []
state = sqwave[0];
for n,s in enumerate(sqwave) : 
    if s != state :
        tchange.append(time[n])
    state = sqwave[n];
print('The signal changes state in times: '+ str(tchange))

#How can we plot this?


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
The signal changes state in times: [3.0, 4.0, 5.0, 8.0, 10.0]
